---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-api-introspection
  namespace: homelab-api
spec:
  encryptedData:
    client-id: AgAVEvkuw/g2hrAsfz60vemvVQkDA/m0kEDYexc6g9KsXuPnUvV+JtRNWwMfQQV93rgO3eT8d047M3WdNIA2u8S0B5IabeEBPgwGvjf/ErktVi7lmCE2RNTFdv4ItEpotkJ6rrZjGCQkiXQUcQnLf3sPfe7N2KfLIEynXpNRz/7jcONptIhMdUiTWvSn3i4taXOcOqH194oKsaLn+rwG3HHIBjiUw9muKH74LamFPNSzn0Ett3D4GQtSDQsdLJbMwkLgK8MptQ4eZNonW++xSWgOhB0iFbPDZ/FxjSjuTiWLoE+BTqSMPuxRTFkYZNIR2wHiZDEfUbzk3uZecWrUnfyuWP2GrISSRC9XGPpQCGGAOfFA6DSxY28nHdgxcZ+P3stnbsxpfllzG3XhmDQNMEOvR/pa0D1nf8dCt4wVrmH+Ct3usz/wuv3Kz1u8kKyGtqbvTogbyTrQzCFmNH/sHMzCtsLWXddup4DcPkLK9205PPQKsda8x2x1e53piddHub3N51H/xxTUA7UByDXoTsnjA2IUWZnlZg6k1930dn5xGxtTfwf/63EQKV/ahjFgaLuLrhg6zmt6mUAGRxbhjpqbGRV+kSP1QNMADbvfKTSUtQsbNj1uZL4Q6QsQfPw67u6Sb+CYN4NFanChxLXtvkE7PY9R1dx0jMnFIRXBAT8SUg8fYcitMeVcJy7bHjtIRfpyckLnFH20fmde5DpYxl2wFpM7
    client-secret: AgAfjWLOVcd8yuZCwWLQsvWHTJEkK83ZYwG9L9K3tayWB+N/3PmqAVRsCtMfMOOUrec/2PRdyf6ww88cg6YJztX2GBK+0mPHnC+dfgu7ZigoHVM1kICiyyb33xBhgZEeHZKq6yZIapi0oX23fMJa0p3i2BuKD/5uJfkKRqmt9voM1p+30sj68vs4sPdju9RkYMzZpDQRjWnMfGR/PncNbdimJ+NcamNTpmT/htdcD9kw96TywJbczOvHl13QPYmICqd9TfLsoumAX7aCI+cCD+gws3eY/aKVAzU+FEm8aAetGf5/W0MnkQF5T4oAdxY4r7irS372bvWZSu+besabwLvcO8P6fEOusxQWsU0ZDdRn523Y46V8hlBpqKkWwM4FD5yfPro3bExRZ4KGQIm6ttnDCkGStq/h0aqjcmsXmG378FVzNIkbHajqMoKRWnk76t/hGMzmngktfUrRvMHh6cxw3QSWh0BgeYDjeWmrDt9EbZNYbn5GHhqjELhYPY/NBFNqfHfyyw9tINc0OXBgt2UG9OQqwjgzZ0ocRehQLMfx8Kbl8oOBIkwRxc/zKm3zWR3cS89qtoWAonWi83onhxcOG5BpoVNKWPW1dWz+2VTgxCPH6aIHIxCO2ulZFI5XoONXYFY8H9NWpdjF3Jinc1E2YxcfV/Gu71s0nMINHE2ZFW7Vx7V1UgLxOGoVWQzNvpIDg1qLyXwT0Zeh/myCaS0SM2v872WQqoSKVUUPGynmf6pgRYIHMpk9vUeizvhDwRg=
  template:
    metadata:
      name: homelab-api-introspection
      namespace: homelab-api
