---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homebridge-mqtt-credentials
  namespace: homebridge
spec:
  encryptedData:
    MQTT_PASSWORD: AgADLLKtBuJvCCAk4dn8qO5zM1okci7NSgc39ZXYaXN3OmWETa9sM8RyyRpYj3eFBFnTOMiW8vhybSIoV9SWExVnuehNAoHzaHDcPzkaVZi6xQg8R3dDXpmwhgIdG5Wf1wC0ANniu969c6XB6EhJfyB4HePWcmOy1SdpWtAIK0AkS/UmG1uH9F+jZhG0w4LA0gUyUz8C9US+P1ElNgpQKBl6enevUxXsYyWYWXN5Lz5z0EU/FE7T9KGZd4qpqADr7c1JI9IJ1FvrSpprq5ea9wqtRRYnB9mXt7iAl0j0S5eap0mtnLHpyhCYp8hTSfcEQ+bqJeFAae2j7YRkerRSMYjgrLmsAS5gL5MOAz0xb/AdMtua/THzTkZqjT4n9+dgZk21a/JWGMfUe5dXbZbcdoYUKaqBSdxQRN3hY/ddrVDYmo54AUMI2An2tElmaoxHLASNJLmMkdguTircwW7boLcy8lg1MC9NAFAFoZJAJI1mNSBbqTESdv69H/8kgBdk2dSW84xUcOZ8yXyTHXsdpUB7IqjEMa0b/GsDm+rAyhOM9Ex5vCaENsnWI57SXpr0htWOKVcaE770VmuPR24egJq4ZzNxx11A1CZywhOlNJSV2TIOyavODBrxOKZwP8VUce9RRGL0EJZsCH2vwzFVeTH6nBNznjPsuS8dzGJhDMor2AyvC+xG4N8VVP2nXMv5+xLXsYIV0Og5I6X4ISMW3I8mccKxfA==
    MQTT_USER: AgBlPhBtiVw0pYEtiGG+Dt77JAO6dknL+K+e/dmXrK8+1pFzQWEnU4tNZGUOqhr1lD/I+ZjQ2NVLsyY82lQB4NMoiBReHq+VfAOrj47Gh6xBwWg49U04PWB3QoYe3BHlRuhEeDYVS5LpT+fCIjE9TDbzwX3WHIO0bpfZ6tcNobcgcuRDc5mXTagaB92JF27D4+VjccAoChSmagje46wl5syn7nLj8hnaGRRrXwKcKeJKndr3U21tTvgmub6W9RqiD/cxMs+ELDrPKSFRwq9icIit/30z5ezBSlrPApP6ObzJ8X6cDWD+sof18Bz/DQMMeulveOFM7rkLAU6qOrF55EX3OPq/35bNdHqzpAfKW4ElGrbbnhBMQZojzuQkXgk+W2BXqzrKJI6VoHi2L5FAaoLTW+RjrUK5rqM13vZQf2jr7Q0DUt1v1Y37z4IGmdFAeMHNDeRXNNOWnSW1lMwWyQlwg6XFJVgxvW2CZ1yrVxoLArCyR+0yFYDfnf83TAz7uLcLBpVXp6F5DMXO/Tj2cNGxdBAjHOkUmgcAPcG+rEQdOjkAZyxHIk0HVDsanRyNSwphUvCmDqEmFPGNkzDjpfLtV8wwD9QhtnVnhl5VLt05OKLrtHqW7KuljjEt9Qzcp3bmaBOIyxTVFHhNBqGXyVuxY/77odIxn61yWUhfrG7yU0P7w6hIxE+KHDFtzIov49NJckQF6g==
  template:
    metadata:
      name: homebridge-mqtt-credentials
      namespace: homebridge
