---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgAXDVLMa6vmtQkI1fFxZfuucLYCfX1k/48c8JIDbR0rPLOUJkTcjMLA6C/HMQ3GbcYj5/+TFDkALetrwBAwnQ5gysYr6EoJ9YiZCfIY2nh0iphynhzpgPrNYEpcATqGrX1BeLDyMaSychZqbxDWW2RnjPg4kFN9ANbuRmIjSMOeVCx9Rlmv8P7XqW5hXKIb8vg3qCBhhShSSkgwVUrRgEOY2Gj+X/r+SW4e1HaHnsusMuZ+8cAaomL+weAFe2j0CtB59m/g+kK/1H+yJL4QK5xVAPh61hO2itHqp2xznxO+ukWMqipkIINAdB955+FsAg9kPXbn3SGw93adDxOzDbLDgRG6MQA00LH+tvHS3pmbsDtvOGd/qgxd4lRe82lydGxDho1Ah3Nz67BPSEMzH/bR0oWeJlZ+EQvRw54UrRhUvVoOD9boKjZIhreX/Rm8l1DHgyhaOMbOik6T3XdDQhRmEWlCi2bUemz8059CMDOMx80BMAJMqpHS8X38rmo+5EzxFZx9fFWpUM1n9vvgd93DMTd+HYsBY+2yKx17FsMhY11GBGhiVDFgZ8OVZGtmSWK5H/zuWEm59qab1IhUNjuBlsrgVMK92fJm1Z14ZCLQhfqbYBGQC8K6It2XaADNMckzlktPe4gPN4QKN3Iv0oJZHkzt7ieW3SWHVl0JXF6CMMUJLkhcUOozbRFiVag6uniL7G8FGePHnQmlMwnjrBJKw1cHTxy2ldyYVOEbLhiOljcIymulr6nKV0UeC5wmwCDiygfB3/IprXLbIaP6rx784pmecyG9gLo7Mxb+JyqD4sEGN0uoA/VjP3P8KL/let5RE+SUxjmHsqOqkl+DUvFUZ8/llaQ6XTjPRwhN23cuvvlbJXFkg7quPtiw9mViN+1uF4C0AJjw5lZRu/lJX6ll3b33B43tMw6u4JpeRJnCsw3eXyBJI+JpXKNUw7epPkYdxvvJDTOPWs2TuaTgdkAxkSS7X0QGDij0T8rlgX/G2Sj5STHb153kJ1grjgGHyzmMeMRZVugbTd8aqNfPnVA4bk3H0VT7jFe3L6ulW5Y/dZq1hvBbrXZ2JwTHBWuJbaM5xYG7yFckOJyK4aOtapWT/U42fNQe3/8J/1tKmJjimAa5i7iUm6Vc1EbBvw6v53xkTlKWLCp7ls9COgLJFymP0lu15PjRNkkXaAt7kBQ3mwyYz+zmfE8a5Zr+VYBmBXBGMyYheuO5LDsgTfYwLK9BGxZg5rJiBedELmw4x0158BB1iQdxQnu3KDdTpZ6Dc+V4OIUsiw2QAJcYZehWG8GHcTXBGD2qR0E4YPVRJa2Y1pko43Y=
  template:
    metadata:
      name: authelia-users
      namespace: authelia
    type: Opaque
