apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - configuration.yaml
  - deployment.yaml
  - authelia-secrets-sealed.yaml
  - authelia-users-sealed.yaml
