---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: timescaledb-credentials
  namespace: spotprice
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAgS8ZGbYX9t41nkn/95JbCVlR/PAZCrqvjMyIYQcxWnVmJo/1O5OnnI9U7ttGFS/EBJs0S2sEvneqFXOD+2y2XFn0luIyf6qdaSfAOoSlsUDUpI70xpqpSSlHNYuQvIyeVmMZaE6qDZ+atqjSKiOw4RFEgIYPdkh8wNt13ro0LaTB+Vy2UT/OnAFkhPocwWh02GrrlxLJUtLUdnjsmDc3wsJYGMQzggGhVUA+cBdZMzWtPrrJBsef5FjM5aH0jVuQIKhjYJbVPoS9sU8LhjOr9o0gjA4OS1YX27t7ejK4GPPeq+f4Rr8ODoD0wA6mYLXVL+MLU3gfjki63VoSpuAXbgPJyJ2SgUUT8t/lsuPzWPCPZArCYmJ6PvRXH5PU7ltcO04XWvNg89ED44p161CKZ48PrRilNhcaAV6ZISg1jv9Q1yuQpIKaSY/rmxsnro3tLMdHCCbacCtNP8M8tAYwuYoQ6ev5plQQ2/hFxYiX2Ox10u3xe9ogC3ds+OLpEe6RTx7ZURqcw1gqFbt/Rt04+bSAeQiwI5lJHk9iG9cMyslnixPxNZPll1SRofCwnqr9ul99OPYizB1rancXRWdSkyMkhVaiPRtPFSNMx1pHa6rxwy6+zuZTET9UpddOZUSpcXDG8zUK4qNLDNqYzWULe80HZGArdpG+tHonD4ejwANjFi8XQ0nil+3WzhggidhbuYZVJjDHqndSUInbCPCxeyKT/lFZX/V3SzztU
    POSTGRES_USER: AgC0cDcZbkBy3ZVDONTqg2i79tfKjo3Cd4yhGiuxAqHFxUSdyODGMgvvNYqBEsV8JGJfxhMxzKLmhm5GH5L2xhJAke68yTt8OhR8nwvtmH/hP8zNN/ZuxcCCs7gj8d7c4T39NcZHARk91Af1ePuyI39AT635wNh3CqQtuf+ciI0h9Kij/Fucdu448Dhp4BZDq+hm8IdR4VifGOz6kUpF+DNdbCjdN1H9iaeI95f5sNEqzWxVnzxlbmCo4iMbgomgAIBqbC1WBoJd+YxD6MzFSRh/+v++oksgZLe0yLS+s0idsc8UwSuU91hUeOkG00OD4iq2NHFjKhY/iy84Fei4x5ljChnWZwzVXTdDeXS//1ogcbzumAOBlZBLA/shs3FQxk0zbi8nNDDKaZX0XRZ3w1+7bTJAAASvlxJ8tYQc/98RiQ/R+rjAa2XNjow2lhMbi8Z6BkNWk3Emc5UZutBVgF5cwSqzk8S4agipgT9pH2mCGp8V79RM7P102bobU1/jHdioD5wxFhqR54bOAQKoWabr/s1lc+4WGNdkINvmWQ/prD8S74Zgtyrvy5PW/mODljOJIap1Dsvss50K70fCd1HoySVU4rKYAkCW0pucydKaK9NOuunupsRJWdVqJt2/m4E8aOCk0/fnTKxEEmluWKIRSsdHqznUYvlimldpAW2s2tirMWLZb5UK0cMnDgbq8kNg8x6pv8mR+A==
  template:
    metadata:
      name: timescaledb-credentials
      namespace: spotprice
