---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: healthchecks-ping
  namespace: monitoring
spec:
  encryptedData:
    HEALTHCHECKS_PING_URL: AgAdQ1xjoq8SU3qxaSMA3AKH3QVFNqVFaq8Gr0Ay48hkbowVQP5wxCZNlRDyEH7xmFZG4ju8qlgTpbOTcwA8CKeUMs+0OGZxuQGENgxen0hRSUQi6AD47neGnxR+sbr3lJIvdmnNecC7hD3c6bBO8Q2oj3/EgXIQNYCNFXFeYVZuW/tQCysOI+5O0fyHmPC2jvcDw4ffM93H/DRxs190qERYOOnbgO4RwhdHPLCY2d9pIXyCrSLZNu6HJdNzYkOFUiz5lIdRZAbanQYnPAjhzf8TKtmUVipgRdL7EPrLmbeG1+w9Ntfz86VK6k/sYL7abbTntFS53E+KpWpHTo+4l4mNjDEXxtBAc8gH6KsiEyyCrwHp50TT+0j+cWmhvtXeLkwokQucubDdHneR0HEbIv6Um+Etc8l6Mcb5mN77BsSwN4nrOjlm71yGXQcSTiv9NvjT7NjEx9V73jQxu8pARurqvf/qPym1LzatvPLwCBQDjB8w1YqgaV1LW2n3DkP9hTjzPLvXX/0BZJR+u9wqZFBVUIOnAEADgcW8FUBVNQnAxjBqNUwwImKPHzAKVuf6yd4D7oFu++tXIlxyH5EHuyHjtrJ+92C0a8J1cQLNj6U7mSKIY95C/uQLT7kq7iJNBAa0rryipTmBve/51FWvCJzFgQgRKGTSJ7C3g1A0lQ/2Rv7o7ycEmcJ2sJEeiAoHtm4ylNnJrSkzISLGnLhQ664qDNDzw6pqf1JBmbRcfNweWGwis7hiADMfyCPWxfyprsCOAO961JUccQ==
  template:
    metadata:
      name: healthchecks-ping
      namespace: monitoring
