---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: healthchecks-watchdog
  namespace: monitoring
spec:
  encryptedData:
    HEALTHCHECKS_WATCHDOG_URL: AgCu46MG5C2MkgF5RP8y4GVRltsj1+oMT8L8l/ar1O32FkaZaHUyCQHxHlAeQ15sdNoXBfiNQWmAGfsONFZbRX8ZuwWSeCxxR3BTsACCFYnlJw74Rl6BF26KzwMg5ezVWb6udWX8m0kqP+L4Dpdtv4Doj5BbX0o7F0tLIni/sIg8uwB4U84wxuckjZKVdslXq+ltMuq209tVvqfjXAaCvw/XH4xKKFfiku/zUxdPgV0fvKdwk1Njt+aXOI0bD1N7+Gvtvf1OzQtZBGPQiBI4lRRpXyUAhSi3C6oA+vCc2F5RTtStW9GzWfke7Pd419LwrTMzgFpm9ZKybybQg3SAtJAzRZ6BgmjF6/ftuIDyPFF/Oh3p2yA0ePTbxp4PCKxVjLK4EeT5csfWFn1dxfKzcb0/32kc+E8035w8/VM7w0Q6+rawlCEsMnn89GN5nL95o+4u/vbJbCYOZAwESObOnHAG/o/fMgX36MLn8QSLbpFEobcdYk0AeozySdXDD7UBL9cvfjJG43rp7Xo1++Y9aQEk2Afw6Clu3zov4m0dJnlqpLA+6gsolz8Am2Pijo7vozENZjiEoU3a33PBQr1ANORqUPkIw7jZm39phdhN89mlsCUWXFiiRokSBEQEx3fpBeg3Z3O1QMrVypD9HfJVNKdLrE8CHZ60Y5G883COPcF787zDk7qhoj+UzvqZ0Gy3iK4cXCQnI3MDkA7PbqTeKPOPQdiEpejPnbHx2CmdDF7ncF8UhccQs6f4omNn2S3oELpYuPOhfhzReQ==
  template:
    metadata:
      name: healthchecks-watchdog
      namespace: monitoring
