---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gasa-api-secrets
  namespace: gasa
spec:
  encryptedData:
    ICAL_TOKEN: AgBLF+nHiMeLPKR+u1F/u7eXw1vTkqCpGODjZ3mXsMDiY48SZiWk6/mowx2DEPRfKuZwaGIqcQT6tvzLtsJZiDWKQvgTIjw2K+E2RJXxOLdyEOYMiDBbMRXRi3p5GKlsSgvEQnj11N3JbjZQB1IFQSvm57+XfWw+wnv11LKAxion4GY06b+qDC2Tom62vzMgBWk5EHjsBmJwdt5YH1UU+mybE2NgF2z28g9j2z6vdnKjyP+z2lkFGwnwsfEyoIpl/2NwO+SuvEiFwjc7wNjjaeMcPbdNqs2+3lrb+D3rJx/3iIxivzKWgsVDLOJNEsBYwKqV3p0p6BgSfMk2eiIWVSegJ9RPfErgLCi9axR4Y6dxgN1cP2uM8BhExSBNcE7ShAKqi0KEQhiorLal4SgOvmN1WTi82A/iewxysQLBg/9GYoWdB/3ibqRh7wjtbK/iv+Qpm1FV2FMY4uNatfTkFToUtgpI7EY4Ga/5SqfxQ9/UToXhE34rZYzHG9Ydt1O8PqpXzD4Gh90F5AwASLmPMHCtd/PPhocVWpLJ41XTUnjSP+NMb1D16p2OHcRQ6ywC/WnZy/AntXhBT12YH+SCWoXyjeCsV+026hqCI76NmHHljOH5lZWmPnprbL+1XmQDQ7qbh8SOg28pltFEp7yKqHIvj0CgIvDtVUF1S3/Ra8P41WfM/zGObHp1i9UZbuzsvXT2cb253sIGPHb6SXJ6pqZPm/ATYMaFa403X2vlS/CB7aY8uMK9S+WhOs84Qs1+p8u6a+1Zr/JsslkpVpn40DXX
    SMTP_PASSWORD: AgCsj+Yh6hDWcT5/mUkEjROW7nm3Sz5Nzz3qoBSmbtlIokSz13CBwXrKJym16N3bWj8ffO2vpYlBM2AYkIL6bDaZ7OvtWJabiA47wYlIONKb2tMw1cHK+vsVSDJ1wsICM1izLh/R2U2Hn4qOWxLsFIRMQcQOPfBWNvwmqB/qXE4d0VA9OHM4tTbSFVTlkJf/MbHcihr/DBHZmgW/83Dk8WZLyM6Rvu4/wqG56foYaOhmJO0TSvDk6EbKXhLZIIn5NE5BirLJlNkEvxS8pSV8KWNgviRCn3HEMyU6Zhy25D2NcSYTx62jEs2+oguLiCDTmoN1d9vOQ6oc3eVg62Kwr2UJQayvwqMYkGKPXPqkPsncIEMhAQP8nbksxk8OG8+IVyJMGsyqktiAO4ILZc/dEU3cBALDtoZiploIUE08wcZZNCQpflIt9OIn+IVEURp/lbppgvY+yLoMae57dcYmHaQUta97E12TKfI5G+Z8UqHbM9PzLHOknDTC5VHcTPgbvqUGbsmOVHNPjyyF6KVLz3WSAhV7ZHoeRbWcG6FuJn8K2ECFy3RH2SMs5G3+JpI7ZI7A2kXZNO+yzlnaWT9kWdTh5jkGu40z/ipN5CzB1FGBheNy5e4wjB48TWpmLyU4DBywgapf4goHhbRZ4pY0cQI+IeTOBXiI3TlAcXG1UewwjG+NEWUqHhi3GIM9eQYz0SI=
  template:
    metadata:
      name: gasa-api-secrets
      namespace: gasa
