---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gasa-api-secrets
  namespace: gasa
spec:
  encryptedData:
    ICAL_TOKEN: AgAFS/pbXvyF7YuQs1GNtSALNEktuQD3lK49Kr2R7eBnoNluwn0Crub3DKlChwHjY//ifg4qjhYVtJXTrQSRBtDCE6iFBhg8/wni+gKb73knnm8pkVDS0odeTz3gJYXOzvsX6S2/9lmhkG12VZU/40EizSLZ9cX+nha7pA27WeGR6AU8gpOVSrQT3it4RWHXTIP96TRD93chA7uqhRcP5f3Ht1gzpRndHbPAOiCrVx+DPX8F0xAVq7jASgV1PD94pOfb665FoclLTL87LKS4o4bJfCCRPGU9RDDbglh9QmETXCngNiha8Cat4l5Xx4eOfBh6C+AXdzpEkmpyvAlwpPLJ/FsyT6d98bLNwkrrHIJMTydIn1pC4kg3tZCS6aKWU5FQoaSvWRKW7WG/iNZ7SipNFg1SZDzItf3GiIfU+lHH9bPw1yi8zPc5M28JAwwiSY79D18/ITa3LpWsRq5RJheCsv0WCES/5cgHznnCr06HCR3d6UTJsP6ePa1rRD0x6Fr0HVYKmhWIPTOJQYymIMMeR/LYa/5LYLNFcXmfYoiMMI3ImR2Thk/WCMoOXvjto1xJ0JtUcVioME7Dpl22HJhg7aldCIbqa+mR/97B6X0eR+K2QEQ6+0kSgs2pRBgPEIHnksLb+WgN90jsJqG833YfSlwXUm78zP6RMi50ZcTAWI8F2jmAjBrTQyFcF46RCCZXbvGZNOCA1tUcCnczCMjTgA4KyowCB9nMoAxx7HMhKhk4FbwZCRAlqS3FWCFlHLdpciqx33fNMqNMm8D7Yecq
    SMTP_PASSWORD: AgALoHMpETsDuTHFAvpSG5OG2W9TK87JSIQNXUS0estT/P8ZnE88vOmOG4yGrdygWJS4Vyjc/EXjndYu15WDp5QDY92/ke22l1EkAFxPNetzwRQzkUyMixXsYgBZUXj96S6BR6tYisqcFA3JxHAo/JpQ8zQCNaOU1AD04PUGuMy4Usk9TcWXIFh2/gj98N1GRUYXvjLI9K62WgaW+zgfE/YaO8CtWkQ5+CAnKyjdvrylY8kvta6/TlFcUsytJAH8flZQOUBLHRDpkClYRxho29+rW2/fGA6yFLHS9xapsInj1aiUS0YrEsx8YiGEBVmFWgfvg1q0J4Zp6+F//fWws+2x6M+GzutHfXrLZpTLW34hVVeyC6psF2p3vBaBxnDTYMw97i3jk/cbGsoHHsn3ob3zS5YlltFMIuymrKXx1RDQnO7m+CLctomq6nFAz7G6sHbkAFVR2OcaFkGO/27ywIuYwFDurIxNkK2RlYZ1J7YAG7K7JeRi1yIYcIyORTwseaG+m0tG0kv28huI5mew33TY91YZ0Mm0I/lbHOkGWhFx1lar+kQ2HNDsjCY/2hgZWjIBv4EDK75cEVBd+c1HGYbf2GgGsq+5AYbQvJtSck0zeutVRN7CrZfrUhwbduWZHQm4/p/Iyz7DyPdwQ3Jaou9FabtWKvDHW4o7h1YXN3iSNumT/k0U/zxmZyiKb5lcLyLqFyCf1b5tehoW4sybdCyw3g8V
  template:
    metadata:
      name: gasa-api-secrets
      namespace: gasa
