---
apiVersion: v1
kind: Service
metadata:
  name: gasa-api
  namespace: gasa
  labels:
    app: gasa-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: gasa-api
