---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: gasa
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAYRv5xr+mCof/i9cW3TU4HQm66sENqrKyyEPomY9IJtLhMzQtgDmpX1TgV0L4lsmX7CBQ0l8F3HXuVZeSozwh5bDwE0udsGRsS1uO9qt8mOJHcTas6PHoAa2MiMh4msqFzkKmZZFgApUrr2LqrSlQqhsMPEsFMb3tc9xWLSDq6gGgD2V9HEjBCWVWRdCTtxzdhZSDYTWcqwK8Nk4ouF8kPI7AcHi61TPPBcM/A/l2GTbwwxWpswb1If78h8+ZJZ917ojbqhWUqPyE377tO93k4zmkC0jkGGi7lfpAwRDH601V5XY6HF2hpZCqX4bIXsY/hA92Q1I1XEH6LwRhJ+w1HylNmua1RzDB3pwwASd/0wMnfRj5P1IxHY4ucFbMtFCCMEqNsZ1KaXOTUepl8XXdRVao7YmbspFH0kDoSWiWhJyHVDh0MuN3S1BkMlHzRGL7g2m2AtNIg04xOU5Rw01b1zo5NA5Z7gmYno7Nksg8dMpEprFoPYuHlJIdC+wfWu3PPZxHLmMyLOJA8MJAWR1hBj79pguEugt09TSoghXTwDYYOWpSPCI0HRqnvdSwrR67dhQtcYu/hOQZtR0HEEQXhfSgahraDX36jTwJgglrnYqDaskRUr31e97n8dMN19kQXtjgy8B7dymAy4d5fG7x5obVjjjfE7i7XvjBZN23IzFVqbqkf4sEjvvAAONYUk0unFNylmeu/TLh8nKkfSnAuUfaqL9uygxS7Kxy9EesWnWf99mZ8U/SZq43wyimuEDw=
    DATABASE_USERNAME: AgAeA0LLumkKOLI335q+4oC102Kp+vl3K3j60RM7vjZnTPtdDniWATDNlsBy4Fx713CgWQI1xlipQfTkwZRqyF3VL9LlZlaZ0eghDJvd6+i5aJDI9E6vCzaW4BsIWmvC6P7h8EV1HBtEIyd9vLMGcPobfuRQa9J8kqY2MsrXbQ2vceamiOKgK9QgofJtPfx7SmOa7H7nzlOZKNm4snMiEXJbfL8YghDvTVkhl1G9Zrw60m2/sqz0Qj4LMsrlbkXX2PSWKH92D0dqQYKR7+249EDeeeApgwioUwZX1z7RKkpxPAVVkWbXQ4nLl4TCpPB3AAxC4jnXbsE3omEf7kICyl2KjSCW8P/rNok6OM3a/rlYJ3fWe67JRwPU/rGHUNNUxDdUYVeRa2tQmXfStfEv8AWrd3vLY1MEEMwu1hk9tbxgVzskZL03xCYDNny4Ry6aDiZ9lZFAFeyCFQ7AKSFcu/MLbkRht+0rDo4XPV/Qpq7HuXdmbcIaBkGcGZh8u7gQb8jhal6vECcUjvDEu/diu7GJ71hziGwMiu3k+Ujq75pLjlyJWgdKJVKLNSYUJT3Z9QEfkBkfUutKZCwNnBwLcNLny0s4apHPe8l+mfRVQ8gfT265LrYCX650Y+oCiJyyQkC/39xBuKeUlY7bRyN50d5sY8aE1963CMWELLrgynKxlhxK19aRiJW0X7H/bNH2Q0WC9Z/71qr9qw==
  template:
    metadata:
      name: postgres-credentials
      namespace: gasa
