#!/bin/bash
# Deep diagnostic for kubelet connectivity issue

echo "=== Deep Connectivity Diagnostics ==="
echo ""

# Get node IPs
P0_IP=$(kubectl get node p0 -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}' 2>/dev/null || echo "192.168.50.210")
P1_IP=$(kubectl get node p1 -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}' 2>/dev/null || echo "192.168.50.211")

echo "Worker node (p0) IP: $P0_IP"
echo "Control plane (p1) IP: $P1_IP"
echo ""

echo "=== Tests to run on CONTROL PLANE (p1) ==="
echo ""
echo "1. Test basic connectivity:"
echo "   ping -c 3 $P0_IP"
echo ""
echo "2. Test kubelet port directly:"
echo "   curl -k https://$P0_IP:10250/healthz"
echo "   curl -k https://$P0_IP:10250/metrics 2>&1 | head -5"
echo ""
echo "3. Check if API server can resolve worker node:"
echo "   kubectl get node p0 -o yaml | grep -A 10 addresses"
echo ""
echo "4. Check API server logs for proxy errors:"
echo "   sudo journalctl -u k3s -n 100 --no-pager | grep -i 'p0\|$P0_IP\|proxy\|502'"
echo ""
echo "5. Check routing:"
echo "   ip route get $P0_IP"
echo "   ip addr show"
echo ""
echo "=== Tests to run on WORKER NODE (p0) ==="
echo ""
echo "1. Verify kubelet is accessible locally:"
echo "   curl -k https://localhost:10250/healthz"
echo "   curl -k https://127.0.0.1:10250/healthz"
echo "   curl -k https://$P0_IP:10250/healthz"
echo ""
echo "2. Check kubelet logs:"
echo "   sudo journalctl -u k3s-agent -n 50 --no-pager | grep -i error"
echo ""
echo "3. Check if kubelet is rejecting connections:"
echo "   sudo ss -tnp | grep 10250"
echo "   sudo netstat -tnp | grep 10250"
echo ""
echo "4. Check iptables rules again:"
echo "   sudo iptables -L INPUT -n -v --line-numbers | head -10"
echo "   sudo iptables -t nat -L -n -v | grep 10250"
echo ""
echo "=== Alternative: Check K3s Configuration ==="
echo ""
echo "On p0, check K3s agent config:"
echo "   sudo cat /etc/rancher/k3s/config.yaml"
echo "   sudo cat /etc/systemd/system/k3s-agent.service"
echo ""
echo "On p1, check K3s server config:"
echo "   sudo cat /etc/rancher/k3s/config.yaml"
echo "   sudo journalctl -u k3s -n 50 --no-pager"

